apiVersion: apps/v1
kind: Deployment
metadata:
  name: press-the-button-deployment
  labels:
    app: frontend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
        - name: frontend-ui
          image: velipekkanurmi/press-the-button-frontend-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 150Mi
---
apiVersion: v1
kind: Service
metadata:
  name: press-the-button-ui
spec:
  type: NodePort # loadBalacer == default service provider loadbalancer in use
  selector:
    app: frontend-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
      name: http
